Add a dummy step for a summary link

diff --git a/.github/workflows/actions_build.yml b/.github/workflows/actions_build.yml
--- a/.github/workflows/actions_build.yml
+++ b/.github/workflows/actions_build.yml
@@ -45,84 +45,104 @@ jobs:
             snapshot: true
 
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - id: setup-jdk
-      if: ${{ matrix.java != 17 }}
-      name: Set up JDK ${{ matrix.java }}
-      uses: actions/setup-java@v2
-      with:
-        distribution: 'temurin'
-        java-version: ${{ matrix.java }}
+      - uses: LouisBrunner/checks-action@v1.2.0
+        name: Build summary
+        if: always()
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          name: Build summary
+          conclusion: ${{ job.status }}
+          details_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
 
-    - id: setup-jdk-17
-      name: Set up JDK 17
-      uses: actions/setup-java@v2
-      with:
-        distribution: 'temurin'
-        java-version: '17'
+      - id: setup-jdk
+        if: ${{ matrix.java != 17 }}
+        name: Set up JDK ${{ matrix.java }}
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'temurin'
+          java-version: ${{ matrix.java }}
 
-    - if: ${{ matrix.on != 'self-hosted' }}
-      name: Restore the cache
-      uses: actions/cache@v2
-      with:
-        path: |
-          ~/.gradle/wrapper
-          ~/.gradle/caches
-        key: build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', '**/build.gradle', 'dependencies.yml', '*/package-lock.json') }}
-        restore-keys: |
-          build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-
-          build-${{ matrix.java }}-${{ runner.os }}-
+      - id: setup-jdk-17
+        name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'temurin'
+          java-version: '17'
 
-    # Build the shaded JARs first so that shading process doesn't incur memory pressure
-    # on other Gradle tasks such as tests.
-    - name: Build with Gradle (Shading only)
-      run: |
-        ./gradlew --no-daemon --stacktrace shadedJar shadedTestJar trimShadedJar \
-        ${{ (matrix.on == 'self-hosted') && '--max-workers=8' || '--max-workers=2' }} --parallel \
-        ${{ matrix.coverage && '-Pcoverage' || '' }} \
-        -PnoLint \
-        -PbuildJdkVersion=17 \
-        -PtestJavaVersion=${{ matrix.java }} \
-        -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
-      shell: bash
+      - if: ${{ matrix.on != 'self-hosted' }}
+        name: Restore the cache
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/.gradle/wrapper
+            ~/.gradle/caches
+          key: build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', '**/build.gradle', 'dependencies.yml', '*/package-lock.json') }}
+          restore-keys: |
+            build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-
+            build-${{ matrix.java }}-${{ runner.os }}-
 
-    - name: Build with Gradle
-      run: |
-        ./gradlew --no-daemon --stacktrace build \
-        ${{ (matrix.on == 'self-hosted') && '--max-workers=8' || '--max-workers=2' }} --parallel \
-        ${{ matrix.coverage && '-Pcoverage' || '' }} \
-        ${{ matrix.leak && '-Pleak' || '' }} \
-        -PnoLint \
-        -PflakyTests=false \
-        -PbuildJdkVersion=17 \
-        -PtestJavaVersion=${{ matrix.java }} \
-        -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
-      shell: bash
+      # Build the shaded JARs first so that shading process doesn't incur memory pressure
+      # on other Gradle tasks such as tests.
+      - name: Build with Gradle (Shading only)
+        run: |
+          ./gradlew --no-daemon --stacktrace shadedJar shadedTestJar trimShadedJar \
+          ${{ (matrix.on == 'self-hosted') && '--max-workers=8' || '--max-workers=2' }} --parallel \
+          ${{ matrix.coverage && '-Pcoverage' || '' }} \
+          -PnoLint \
+          -PbuildJdkVersion=17 \
+          -PtestJavaVersion=${{ matrix.java }} \
+          -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
+        shell: bash
 
-    - if: ${{ matrix.snapshot && github.ref_name == 'master' }}
-      name: Publish snapshots
-      run: |
-        ./gradlew --no-daemon --stacktrace --max-workers=1 publish
-      env:
-        # Should not use '-P' option with 'secrets' that can cause unexpected results
-        # if secret values contains white spaces or new lines.
-        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USER_NAME }}
-        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
-        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
-        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
-        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
-      shell: bash
+      - name: Build with Gradle
+        run: |
+          ./gradlew --no-daemon --stacktrace build \
+          ${{ (matrix.on == 'self-hosted') && '--max-workers=8' || '--max-workers=2' }} --parallel \
+          ${{ matrix.coverage && '-Pcoverage' || '' }} \
+          ${{ matrix.leak && '-Pleak' || '' }} \
+          -PnoLint \
+          -PflakyTests=false \
+          -PbuildJdkVersion=17 \
+          -PtestJavaVersion=${{ matrix.java }} \
+          -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
+        shell: bash
 
-    - name: Clean up the cache
-      # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
-      # Restoring these files from a GitHub Actions cache might cause problems for future builds.
-      run: |
-        rm -fr ~/.gradle/caches/[0-9]* || true
-        rm -fr ~/.gradle/caches/journal-* || true
-        rm -fr ~/.gradle/caches/transforms-* || true
-        rm -f ~/.gradle/caches/*/*.lock || true
-        rm -f ~/.gradle/caches/*/gc.properties || true
+      - if: ${{ matrix.snapshot && github.ref_name == 'master' }}
+        name: Publish snapshots
+        run: |
+          ./gradlew --no-daemon --stacktrace --max-workers=1 publish
+        env:
+          # Should not use '-P' option with 'secrets' that can cause unexpected results
+          # if secret values contains white spaces or new lines.
+          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USER_NAME }}
+          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
+          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
+          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
+          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
+        shell: bash
+
+      - name: Summarize the failed tests
+        if: failure()
+        run: |
+          ./gradlew --no-daemon --stacktrace --max-workers=1 summarizeFailedTests
+          SUMMARY_FILE = "build/failed-tests-summary.txt"
+          if test -f "$SUMMARY_FILE"; then
+            echo '### 🔴 Failed tests\n' > $GITHUB_STEP_SUMMARY
+            cat $SUMMARY_FILE >> $GITHUB_STEP_SUMMARY
+          fi
+        shell: bash
+
+      - name: Clean up the cache
+        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
+        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
+        run: |
+          rm -fr ~/.gradle/caches/[0-9]* || true
+          rm -fr ~/.gradle/caches/journal-* || true
+          rm -fr ~/.gradle/caches/transforms-* || true
+          rm -f ~/.gradle/caches/*/*.lock || true
+          rm -f ~/.gradle/caches/*/gc.properties || true
       shell: bash
 
     - name: Dump stuck threads
@@ -137,15 +157,6 @@ jobs:
     - name: Collect the test reports
       if: failure()
       run: find . '(' -name 'java_pid*.hprof' -or -name 'hs_err_*.log' -or -path '*/build/reports/tests' -or -path '*/build/test-results' ')' -exec tar rf "reports-JVM-${{ matrix.java }}.tar" {} ';'
-      shell: bash
-
-    - name: Summarize the failed tests
-      if: failure()
-      run: |
-        if test -f "summarized-failed-tests.txt"; then
-          echo '### 🔴 Failed tests\n' > $GITHUB_STEP_SUMMARY
-          cat summarized-failed-tests.txt >> $GITHUB_STEP_SUMMARY
-        fi
       shell: bash
 
     - name: Upload the artifacts
